# ============================================================
# Nginx 边缘网关 Dockerfile (带 ModSecurity WAF)
# ============================================================
FROM nginx:1.27-alpine AS base
RUN apk add --no-cache libstdc++ libgcc

# 编译安装 ModSecurity 动态模块
FROM base AS builder
RUN apk add --no-cache --virtual .build-deps \
    gcc g++ make libc-dev pcre-dev zlib-dev openssl-dev \
    linux-headers git libtool automake autoconf \
    curl-dev geoip-dev libxml2-dev yajl-dev ssdeep-dev \
    lua-dev lmdb-dev libmaxminddb-dev
WORKDIR /build
RUN git clone --depth 1 https://github.com/owasp-modsecurity/ModSecurity.git && \
    cd ModSecurity && git submodule init && git submodule update && \
    ./build.sh && ./configure --prefix=/usr/local/modsecurity && \
    make -j$(nproc) && make install
RUN git clone --depth 1 https://github.com/owasp-modsecurity/ModSecurity-nginx.git && \
    curl -sL https://nginx.org/download/nginx-1.27.0.tar.gz | tar xz && \
    cd nginx-1.27.0 && ./configure --with-compat --add-dynamic-module=../ModSecurity-nginx && \
    make modules && cp objs/ngx_http_modsecurity_module.so /usr/share/nginx/modules/

FROM base
COPY --from=builder /usr/share/nginx/modules/ngx_http_modsecurity_module.so /etc/nginx/modules/
COPY --from=builder /usr/local/modsecurity /usr/local/modsecurity
RUN echo 'load_module modules/ngx_http_modsecurity_module.so;' > /etc/nginx/modules-enabled/modsecurity.conf
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
