apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: beike-admin

resources:
  - base/namespace.yml
  - base/configmap.yml
  - app/deployment.yml
  - app/service.yml
  - app/hpa.yml
  - app/ingress.yml

images:
  - name: beike-admin
    newTag: v4.0.0

commonLabels:
  app.kubernetes.io/part-of: beike-admin
  app.kubernetes.io/managed-by: kustomize
