# Redis Sentinel 哨兵模式配置 (高可用)
port 26379
sentinel monitor beike-redis-master redis-master 6379 2
sentinel down-after-milliseconds beike-redis-master 5000
sentinel failover-timeout beike-redis-master 15000
sentinel parallel-syncs beike-redis-master 1
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
